//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Biomind.Data.Repositories.Base;
using Biomind.Data.Models;
using Biomind.Data.Models.Base;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Xml;
using MySqlConnector;

namespace Biomind.Data.Repositories
{
    public partial interface Iorganisation_data__categoryRepository : IPkRepository<organisation_data__categoryDbModel>
    {
		organisation_data__categoryDbModel Get(long id);
		IEnumerable<organisation_data__categoryDbModel> Get(List<long> ids);
		IEnumerable<organisation_data__categoryDbModel> Get(params long[] ids);
		
        long GetMaxId();
		bool Delete(long id);
		bool Delete(IEnumerable<long> ids);

        bool DeleteBycode(string code);
        bool DeleteByname(string name);
        bool DeleteBylast_modified_by(string last_modified_by);
        bool DeleteByis_deleted(bool is_deleted);
        bool DeleteBycreated(DateTime created);
        bool DeleteBylast_modified(DateTime last_modified);
        bool DeleteBycategory_group_id(long category_group_id);
        bool DeleteBycreated_by(string created_by);
        bool DeleteBycolour_number(short colour_number);
        bool DeleteByis_system(bool is_system);

        IEnumerable<organisation_data__categoryDbModel> Search(
            string code = null,
            string name = null,
            string last_modified_by = null,
            bool? is_deleted = null,
            DateTime? created = null,
            DateTime? last_modified = null,
            long? category_group_id = null,
            string created_by = null,
            short? colour_number = null,
            bool? is_system = null);

        IEnumerable<organisation_data__categoryDbModel> FindBycode(string code);
        IEnumerable<organisation_data__categoryDbModel> FindBycode(FindComparison comparison, string code);
        IEnumerable<organisation_data__categoryDbModel> FindByname(string name);
        IEnumerable<organisation_data__categoryDbModel> FindByname(FindComparison comparison, string name);
        IEnumerable<organisation_data__categoryDbModel> FindBylast_modified_by(string last_modified_by);
        IEnumerable<organisation_data__categoryDbModel> FindBylast_modified_by(FindComparison comparison, string last_modified_by);
        IEnumerable<organisation_data__categoryDbModel> FindByis_deleted(bool is_deleted);
        IEnumerable<organisation_data__categoryDbModel> FindByis_deleted(FindComparison comparison, bool is_deleted);
        IEnumerable<organisation_data__categoryDbModel> FindBycreated(DateTime created);
        IEnumerable<organisation_data__categoryDbModel> FindBycreated(FindComparison comparison, DateTime created);
        IEnumerable<organisation_data__categoryDbModel> FindBylast_modified(DateTime last_modified);
        IEnumerable<organisation_data__categoryDbModel> FindBylast_modified(FindComparison comparison, DateTime last_modified);
        IEnumerable<organisation_data__categoryDbModel> FindBycategory_group_id(long category_group_id);
        IEnumerable<organisation_data__categoryDbModel> FindBycategory_group_id(FindComparison comparison, long category_group_id);
        IEnumerable<organisation_data__categoryDbModel> FindBycreated_by(string created_by);
        IEnumerable<organisation_data__categoryDbModel> FindBycreated_by(FindComparison comparison, string created_by);
        IEnumerable<organisation_data__categoryDbModel> FindBycolour_number(short colour_number);
        IEnumerable<organisation_data__categoryDbModel> FindBycolour_number(FindComparison comparison, short colour_number);
        IEnumerable<organisation_data__categoryDbModel> FindByis_system(bool is_system);
        IEnumerable<organisation_data__categoryDbModel> FindByis_system(FindComparison comparison, bool is_system);
    }
    public partial class organisation_data__categoryRepository : BaseRepository<organisation_data__categoryDbModel>, Iorganisation_data__categoryRepository
    {

        partial void InitializeExtension();
        
		public organisation_data__categoryRepository(string connectionString) : this(connectionString, exception => { }) { }
		public organisation_data__categoryRepository(string connectionString, Action<Exception> logMethod) 
			: base(connectionString, logMethod, organisation_data__categoryDbModel.Schema, organisation_data__categoryDbModel.TableName, organisation_data__categoryDbModel.Columns)
		{
			InitializeExtension();
		}


        public organisation_data__categoryDbModel Get(long id)
        {
            return Where("id", Comparison.Equals, id).Results().FirstOrDefault();
        }

        public IEnumerable<organisation_data__categoryDbModel> Get(List<long> ids)
        {
            var toReturn = new List<organisation_data__categoryDbModel>();
            if (!ids.Any()) return toReturn;
            toReturn.AddRange(Where("id", Comparison.In, ids).Results()); 
            return toReturn;
        }

        public IEnumerable<organisation_data__categoryDbModel> Get(params long[] ids)
        {
            return Get(ids.ToList());
        }

        public long GetMaxId()
        {
            using (var cn = new MySqlConnection(ConnectionString))
            {
                using (var cmd = CreateCommand(cn, "SELECT ISNULL(MAX(id), 0) FROM organisation_data__category"))
                {
                    cn.Open();
                    return (long)cmd.ExecuteScalar();
                }
            }
        }
        public override IEnumerable<organisation_data__categoryDbModel> GetAll()
        {
            var query = $@"SELECT * FROM `democlient`.`organisation_data__category`
";
            return ExecuteSql(query);
        }



       public override bool Create(organisation_data__categoryDbModel item)
        {
            //Validation
            if (item == null)
                return false;

            var validationErrors = item.Validate();
            if (validationErrors.Any())
                throw new ValidationException(validationErrors);

            var createdKeys = BaseCreate(
                    item.id,
                    item.code,
                    item.name,
                    item.last_modified_by,
                    item.is_deleted,
                    item.created,
                    item.last_modified,
                    item.category_group_id,
                    item.created_by,
                    item.colour_number,
                    item.is_system);
            if (createdKeys.Count != organisation_data__categoryDbModel.Columns.Count(x => x.PrimaryKey))
                return false;

            item.id = System.Int64.Parse(createdKeys.First().Value.ToString());
            item.ResetDirty();

            return true;
        }

        public override bool BulkCreate(params organisation_data__categoryDbModel[] items)
        {
            if (!items.Any())
                return false;

            var validationErrors = items.SelectMany(x => x.Validate()).ToList();
            if (validationErrors.Any())
                throw new ValidationException(validationErrors);

			var dt = new DataTable();
			foreach (var mergeColumn in organisation_data__categoryDbModel.Columns.Where(x => !x.PrimaryKey || x.PrimaryKey && !x.Identity))
				dt.Columns.Add(mergeColumn.ColumnName, mergeColumn.ValueType);

			foreach (var item in items)
			{
				dt.Rows.Add(
                    item.id,
                    item.code,
                    item.name,
                    item.last_modified_by,
                    item.is_deleted,
                    item.created,
                    item.last_modified,
                    item.category_group_id,
                    item.created_by,
                    item.colour_number,
                    item.is_system);
			}

			if (BulkInsert(dt))
			{
				return true;
			}
			return false;
        }
        public override bool BulkCreate(List<organisation_data__categoryDbModel> items)
        {
            return BulkCreate(items.ToArray());
        }

        public bool Update(organisation_data__categoryDbModel item, bool clearDirty = true)
        {
            if (item == null)
                return false;

            var validationErrors = item.Validate();
            if (validationErrors.Any())
                throw new ValidationException(validationErrors);

            var success = BaseUpdate(item.DirtyColumns, 
                item.id, item.code, item.name, item.last_modified_by, item.is_deleted, 
				item.created, item.last_modified, item.category_group_id, item.created_by, item.colour_number, 
				item.is_system);

            if (success && clearDirty)
                item.ResetDirty();

            return success;
        }


 
 
       public bool Delete(organisation_data__categoryDbModel item)
        {
            if (item == null)
                return false;

            var deleteColumn = new DeleteColumn("id", item.id, MySqlDbType.Int64);

            if (BaseDelete(deleteColumn, out var items))
            {
                return true;
            }
            return false;
        }
        public bool Delete(IEnumerable<organisation_data__categoryDbModel> items)
        {
            if (!items.Any()) return true;
            var deleteValues = new List<object>();
            foreach (var item in items)
            {
                deleteValues.Add(item.id);
            }

            if (BaseDelete("id", deleteValues))
            {
                return true;
            }
            return false;
        }

        public bool Delete(long id)
        {
            if (Delete(new organisation_data__categoryDbModel { id = id }))
            {
                return true;
            }
            return false;
        }

        public bool Delete(IEnumerable<long> ids)
        {
            if (!ids.Any()) return true;
            var deleteValues = new List<object>();
            deleteValues.AddRange(ids.Cast<object>());
            if (BaseDelete("id", deleteValues))
            {
                return true;
            }
            return false;
        }
 
        public bool DeleteBycode(string code)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__categoryDbModel.code), code, MySqlDbType.VarChar), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteByname(string name)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__categoryDbModel.name), name, MySqlDbType.VarChar), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteBylast_modified_by(string last_modified_by)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__categoryDbModel.last_modified_by), last_modified_by, MySqlDbType.VarChar), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteByis_deleted(bool is_deleted)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__categoryDbModel.is_deleted), is_deleted, MySqlDbType.Bit), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteBycreated(DateTime created)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__categoryDbModel.created), created, MySqlDbType.Timestamp), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteBylast_modified(DateTime last_modified)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__categoryDbModel.last_modified), last_modified, MySqlDbType.Timestamp), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteBycategory_group_id(long category_group_id)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__categoryDbModel.category_group_id), category_group_id, MySqlDbType.Int64), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteBycreated_by(string created_by)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__categoryDbModel.created_by), created_by, MySqlDbType.VarChar), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteBycolour_number(short colour_number)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__categoryDbModel.colour_number), colour_number, MySqlDbType.Int16), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteByis_system(bool is_system)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__categoryDbModel.is_system), is_system, MySqlDbType.Bit), out var items))
            {
                return true;
			}
			return false;
		}


        public bool Merge(List<organisation_data__categoryDbModel> items)
        {

            var mergeTable = new List<object[]>();
            var updates = items.Where(x => x.id != default).GroupBy(x => x.id).Select(x => x.Last());
            foreach (var item in items.Where(x => x.id == default).Union(updates))
            {
                mergeTable.Add(new object[]
                {
					item.id,
					item.code, item.DirtyColumns.Contains("code"),
					item.name, item.DirtyColumns.Contains("name"),
					item.last_modified_by, item.DirtyColumns.Contains("last_modified_by"),
					item.is_deleted, item.DirtyColumns.Contains("is_deleted"),
					item.created, item.DirtyColumns.Contains("created"),
					item.last_modified, item.DirtyColumns.Contains("last_modified"),
					item.category_group_id, item.DirtyColumns.Contains("category_group_id"),
					item.created_by, item.DirtyColumns.Contains("created_by"),
					item.colour_number, item.DirtyColumns.Contains("colour_number"),
					item.is_system, item.DirtyColumns.Contains("is_system")

                });
            }
            return BaseMerge(mergeTable);
        }
        public bool Merge(string csvPath)
        {
            var mergeTable = new List<object[]>();
            using (var sr = new StreamReader(csvPath))
            {
                var line = sr.ReadLine();
                if (line == null) return false;

                var firstItem = line.Split(',')[0];
                if (firstItem == "id")
                {
                    //CSV has headers
                    //Run to the next line
                    line = sr.ReadLine();
                    if (line == null) return true;
                }

                do
                {
                    var blocks = line.Split(',');
                    mergeTable.Add(new object[]
                    {
                        Cast<long>(blocks[0]),
                        Cast<long>(blocks[1]), true,
                    });
                } while ((line = sr.ReadLine()) != null);


                return BaseMerge(mergeTable);
            }
        }


        public IEnumerable<organisation_data__categoryDbModel> Search(
            string code = null,
            string name = null,
            string last_modified_by = null,
            bool? is_deleted = null,
            DateTime? created = null,
            DateTime? last_modified = null,
            long? category_group_id = null,
            string created_by = null,
            short? colour_number = null,
            bool? is_system = null)
        {
            var queries = new List<QueryItem>();

            if (code != null)
            queries.Add(new QueryItem(nameof(organisation_data__categoryDbModel.code), code));
            if (name != null)
            queries.Add(new QueryItem(nameof(organisation_data__categoryDbModel.name), name));
            if (last_modified_by != null)
            queries.Add(new QueryItem(nameof(organisation_data__categoryDbModel.last_modified_by), last_modified_by));
            if (is_deleted.HasValue)
            queries.Add(new QueryItem(nameof(organisation_data__categoryDbModel.is_deleted), is_deleted));
            if (created.HasValue)
            queries.Add(new QueryItem(nameof(organisation_data__categoryDbModel.created), created));
            if (last_modified.HasValue)
            queries.Add(new QueryItem(nameof(organisation_data__categoryDbModel.last_modified), last_modified));
            if (category_group_id.HasValue)
            queries.Add(new QueryItem(nameof(organisation_data__categoryDbModel.category_group_id), category_group_id));
            if (created_by != null)
            queries.Add(new QueryItem(nameof(organisation_data__categoryDbModel.created_by), created_by));
            if (colour_number.HasValue)
            queries.Add(new QueryItem(nameof(organisation_data__categoryDbModel.colour_number), colour_number));
            if (is_system.HasValue)
            queries.Add(new QueryItem(nameof(organisation_data__categoryDbModel.is_system), is_system));

            return BaseSearch(queries);
        }


 
        public IEnumerable<organisation_data__categoryDbModel> FindBycode(string code)
        {
            return FindBycode(FindComparison.Equals, code);
        }

        public IEnumerable<organisation_data__categoryDbModel> FindBycode(FindComparison comparison, string code)
        {
            var items = Where(nameof(organisation_data__categoryDbModel.code), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), code).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__categoryDbModel> FindByname(string name)
        {
            return FindByname(FindComparison.Equals, name);
        }

        public IEnumerable<organisation_data__categoryDbModel> FindByname(FindComparison comparison, string name)
        {
            var items = Where(nameof(organisation_data__categoryDbModel.name), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), name).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__categoryDbModel> FindBylast_modified_by(string last_modified_by)
        {
            return FindBylast_modified_by(FindComparison.Equals, last_modified_by);
        }

        public IEnumerable<organisation_data__categoryDbModel> FindBylast_modified_by(FindComparison comparison, string last_modified_by)
        {
            var items = Where(nameof(organisation_data__categoryDbModel.last_modified_by), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), last_modified_by).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__categoryDbModel> FindByis_deleted(bool is_deleted)
        {
            return FindByis_deleted(FindComparison.Equals, is_deleted);
        }

        public IEnumerable<organisation_data__categoryDbModel> FindByis_deleted(FindComparison comparison, bool is_deleted)
        {
            var items = Where(nameof(organisation_data__categoryDbModel.is_deleted), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), is_deleted).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__categoryDbModel> FindBycreated(DateTime created)
        {
            return FindBycreated(FindComparison.Equals, created);
        }

        public IEnumerable<organisation_data__categoryDbModel> FindBycreated(FindComparison comparison, DateTime created)
        {
            var items = Where(nameof(organisation_data__categoryDbModel.created), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), created).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__categoryDbModel> FindBylast_modified(DateTime last_modified)
        {
            return FindBylast_modified(FindComparison.Equals, last_modified);
        }

        public IEnumerable<organisation_data__categoryDbModel> FindBylast_modified(FindComparison comparison, DateTime last_modified)
        {
            var items = Where(nameof(organisation_data__categoryDbModel.last_modified), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), last_modified).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__categoryDbModel> FindBycategory_group_id(long category_group_id)
        {
            return FindBycategory_group_id(FindComparison.Equals, category_group_id);
        }

        public IEnumerable<organisation_data__categoryDbModel> FindBycategory_group_id(FindComparison comparison, long category_group_id)
        {
            var items = Where(nameof(organisation_data__categoryDbModel.category_group_id), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), category_group_id).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__categoryDbModel> FindBycreated_by(string created_by)
        {
            return FindBycreated_by(FindComparison.Equals, created_by);
        }

        public IEnumerable<organisation_data__categoryDbModel> FindBycreated_by(FindComparison comparison, string created_by)
        {
            var items = Where(nameof(organisation_data__categoryDbModel.created_by), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), created_by).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__categoryDbModel> FindBycolour_number(short colour_number)
        {
            return FindBycolour_number(FindComparison.Equals, colour_number);
        }

        public IEnumerable<organisation_data__categoryDbModel> FindBycolour_number(FindComparison comparison, short colour_number)
        {
            var items = Where(nameof(organisation_data__categoryDbModel.colour_number), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), colour_number).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__categoryDbModel> FindByis_system(bool is_system)
        {
            return FindByis_system(FindComparison.Equals, is_system);
        }

        public IEnumerable<organisation_data__categoryDbModel> FindByis_system(FindComparison comparison, bool is_system)
        {
            var items = Where(nameof(organisation_data__categoryDbModel.is_system), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), is_system).Results();
			return items;
        }


        public override organisation_data__categoryDbModel ToItem(DataRow row, bool skipBase)
        {
            var item = new organisation_data__categoryDbModel();
            item.id = GetInt64(row, "id");
            item.code = GetString(row, "code");
            item.name = GetString(row, "name");
            item.last_modified_by = GetString(row, "last_modified_by");
            item.is_deleted = GetBoolean(row, "is_deleted");
            item.created = GetDateTime(row, "created");
            item.last_modified = GetDateTime(row, "last_modified");
            item.category_group_id = GetNullableInt64(row, "category_group_id");
            item.created_by = GetString(row, "created_by");
            item.colour_number = GetInt16(row, "colour_number");
            item.is_system = GetBoolean(row, "is_system");

            item.ResetDirty();
            return item;
        }

		public override TK ToItem<TK>(DataRow row, bool skipBase)
		{
            var item = new TK();
            item.id = GetInt64(row, "id");
            item.code = GetString(row, "code");
            item.name = GetString(row, "name");
            item.last_modified_by = GetString(row, "last_modified_by");
            item.is_deleted = GetBoolean(row, "is_deleted");
            item.created = GetDateTime(row, "created");
            item.last_modified = GetDateTime(row, "last_modified");
            item.category_group_id = GetNullableInt64(row, "category_group_id");
            item.created_by = GetString(row, "created_by");
            item.colour_number = GetInt16(row, "colour_number");
            item.is_system = GetBoolean(row, "is_system");

			item.ResetDirty();
			return item as TK;
		}

    }
}