//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Biomind.Data.Repositories.Base;
using Biomind.Data.Models;
using Biomind.Data.Models.Base;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Xml;
using MySqlConnector;

namespace Biomind.Data.Repositories
{
    public partial interface Iorganisation_data__entityRepository : IPkRepository<organisation_data__entityDbModel>
    {
		organisation_data__entityDbModel Get(long id);
		IEnumerable<organisation_data__entityDbModel> Get(List<long> ids);
		IEnumerable<organisation_data__entityDbModel> Get(params long[] ids);
		
        long GetMaxId();
		bool Delete(long id);
		bool Delete(IEnumerable<long> ids);

        bool DeleteBycode(string code);
        bool DeleteByname(string name);
        bool DeleteByentity_definition_id(long entity_definition_id);
        bool DeleteByis_deleted(bool is_deleted);
        bool DeleteBycreated(DateTime created);
        bool DeleteBylast_modified(DateTime last_modified);
        bool DeleteByall_identifiers(string all_identifiers);
        bool DeleteByall_attributes(string all_attributes);
        bool DeleteBycreated_by(string created_by);
        bool DeleteBylast_modified_by(string last_modified_by);

        IEnumerable<organisation_data__entityDbModel> Search(
            string code = null,
            string name = null,
            long? entity_definition_id = null,
            bool? is_deleted = null,
            DateTime? created = null,
            DateTime? last_modified = null,
            string all_identifiers = null,
            string all_attributes = null,
            string created_by = null,
            string last_modified_by = null);

        IEnumerable<organisation_data__entityDbModel> FindBycode(string code);
        IEnumerable<organisation_data__entityDbModel> FindBycode(FindComparison comparison, string code);
        IEnumerable<organisation_data__entityDbModel> FindByname(string name);
        IEnumerable<organisation_data__entityDbModel> FindByname(FindComparison comparison, string name);
        IEnumerable<organisation_data__entityDbModel> FindByentity_definition_id(long entity_definition_id);
        IEnumerable<organisation_data__entityDbModel> FindByentity_definition_id(FindComparison comparison, long entity_definition_id);
        IEnumerable<organisation_data__entityDbModel> FindByis_deleted(bool is_deleted);
        IEnumerable<organisation_data__entityDbModel> FindByis_deleted(FindComparison comparison, bool is_deleted);
        IEnumerable<organisation_data__entityDbModel> FindBycreated(DateTime created);
        IEnumerable<organisation_data__entityDbModel> FindBycreated(FindComparison comparison, DateTime created);
        IEnumerable<organisation_data__entityDbModel> FindBylast_modified(DateTime last_modified);
        IEnumerable<organisation_data__entityDbModel> FindBylast_modified(FindComparison comparison, DateTime last_modified);
        IEnumerable<organisation_data__entityDbModel> FindByall_identifiers(string all_identifiers);
        IEnumerable<organisation_data__entityDbModel> FindByall_identifiers(FindComparison comparison, string all_identifiers);
        IEnumerable<organisation_data__entityDbModel> FindByall_attributes(string all_attributes);
        IEnumerable<organisation_data__entityDbModel> FindByall_attributes(FindComparison comparison, string all_attributes);
        IEnumerable<organisation_data__entityDbModel> FindBycreated_by(string created_by);
        IEnumerable<organisation_data__entityDbModel> FindBycreated_by(FindComparison comparison, string created_by);
        IEnumerable<organisation_data__entityDbModel> FindBylast_modified_by(string last_modified_by);
        IEnumerable<organisation_data__entityDbModel> FindBylast_modified_by(FindComparison comparison, string last_modified_by);
    }
    public partial class organisation_data__entityRepository : BaseRepository<organisation_data__entityDbModel>, Iorganisation_data__entityRepository
    {

        partial void InitializeExtension();
        
		public organisation_data__entityRepository(string connectionString) : this(connectionString, exception => { }) { }
		public organisation_data__entityRepository(string connectionString, Action<Exception> logMethod) 
			: base(connectionString, logMethod, organisation_data__entityDbModel.Schema, organisation_data__entityDbModel.TableName, organisation_data__entityDbModel.Columns)
		{
			InitializeExtension();
		}


        public organisation_data__entityDbModel Get(long id)
        {
            return Where("id", Comparison.Equals, id).Results().FirstOrDefault();
        }

        public IEnumerable<organisation_data__entityDbModel> Get(List<long> ids)
        {
            var toReturn = new List<organisation_data__entityDbModel>();
            if (!ids.Any()) return toReturn;
            toReturn.AddRange(Where("id", Comparison.In, ids).Results()); 
            return toReturn;
        }

        public IEnumerable<organisation_data__entityDbModel> Get(params long[] ids)
        {
            return Get(ids.ToList());
        }

        public long GetMaxId()
        {
            using (var cn = new MySqlConnection(ConnectionString))
            {
                using (var cmd = CreateCommand(cn, "SELECT ISNULL(MAX(id), 0) FROM organisation_data__entity"))
                {
                    cn.Open();
                    return (long)cmd.ExecuteScalar();
                }
            }
        }
        public override IEnumerable<organisation_data__entityDbModel> GetAll()
        {
            var query = $@"SELECT * FROM `democlient`.`organisation_data__entity`
";
            return ExecuteSql(query);
        }



       public override bool Create(organisation_data__entityDbModel item)
        {
            //Validation
            if (item == null)
                return false;

            var validationErrors = item.Validate();
            if (validationErrors.Any())
                throw new ValidationException(validationErrors);

            var createdKeys = BaseCreate(
                    item.id,
                    item.code,
                    item.name,
                    item.entity_definition_id,
                    item.is_deleted,
                    item.created,
                    item.last_modified,
                    item.all_identifiers,
                    item.all_attributes,
                    item.created_by,
                    item.last_modified_by);
            if (createdKeys.Count != organisation_data__entityDbModel.Columns.Count(x => x.PrimaryKey))
                return false;

            item.id = System.Int64.Parse(createdKeys.First().Value.ToString());
            item.ResetDirty();

            return true;
        }

        public override bool BulkCreate(params organisation_data__entityDbModel[] items)
        {
            if (!items.Any())
                return false;

            var validationErrors = items.SelectMany(x => x.Validate()).ToList();
            if (validationErrors.Any())
                throw new ValidationException(validationErrors);

			var dt = new DataTable();
			foreach (var mergeColumn in organisation_data__entityDbModel.Columns.Where(x => !x.PrimaryKey || x.PrimaryKey && !x.Identity))
				dt.Columns.Add(mergeColumn.ColumnName, mergeColumn.ValueType);

			foreach (var item in items)
			{
				dt.Rows.Add(
                    item.id,
                    item.code,
                    item.name,
                    item.entity_definition_id,
                    item.is_deleted,
                    item.created,
                    item.last_modified,
                    item.all_identifiers,
                    item.all_attributes,
                    item.created_by,
                    item.last_modified_by);
			}

			if (BulkInsert(dt))
			{
				return true;
			}
			return false;
        }
        public override bool BulkCreate(List<organisation_data__entityDbModel> items)
        {
            return BulkCreate(items.ToArray());
        }

        public bool Update(organisation_data__entityDbModel item, bool clearDirty = true)
        {
            if (item == null)
                return false;

            var validationErrors = item.Validate();
            if (validationErrors.Any())
                throw new ValidationException(validationErrors);

            var success = BaseUpdate(item.DirtyColumns, 
                item.id, item.code, item.name, item.entity_definition_id, item.is_deleted, 
				item.created, item.last_modified, item.all_identifiers, item.all_attributes, item.created_by, 
				item.last_modified_by);

            if (success && clearDirty)
                item.ResetDirty();

            return success;
        }


 
 
       public bool Delete(organisation_data__entityDbModel item)
        {
            if (item == null)
                return false;

            var deleteColumn = new DeleteColumn("id", item.id, MySqlDbType.Int64);

            if (BaseDelete(deleteColumn, out var items))
            {
                return true;
            }
            return false;
        }
        public bool Delete(IEnumerable<organisation_data__entityDbModel> items)
        {
            if (!items.Any()) return true;
            var deleteValues = new List<object>();
            foreach (var item in items)
            {
                deleteValues.Add(item.id);
            }

            if (BaseDelete("id", deleteValues))
            {
                return true;
            }
            return false;
        }

        public bool Delete(long id)
        {
            if (Delete(new organisation_data__entityDbModel { id = id }))
            {
                return true;
            }
            return false;
        }

        public bool Delete(IEnumerable<long> ids)
        {
            if (!ids.Any()) return true;
            var deleteValues = new List<object>();
            deleteValues.AddRange(ids.Cast<object>());
            if (BaseDelete("id", deleteValues))
            {
                return true;
            }
            return false;
        }
 
        public bool DeleteBycode(string code)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__entityDbModel.code), code, MySqlDbType.VarChar), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteByname(string name)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__entityDbModel.name), name, MySqlDbType.VarChar), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteByentity_definition_id(long entity_definition_id)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__entityDbModel.entity_definition_id), entity_definition_id, MySqlDbType.Int64), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteByis_deleted(bool is_deleted)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__entityDbModel.is_deleted), is_deleted, MySqlDbType.Bit), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteBycreated(DateTime created)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__entityDbModel.created), created, MySqlDbType.Timestamp), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteBylast_modified(DateTime last_modified)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__entityDbModel.last_modified), last_modified, MySqlDbType.Timestamp), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteByall_identifiers(string all_identifiers)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__entityDbModel.all_identifiers), all_identifiers, MySqlDbType.Text), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteByall_attributes(string all_attributes)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__entityDbModel.all_attributes), all_attributes, MySqlDbType.Text), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteBycreated_by(string created_by)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__entityDbModel.created_by), created_by, MySqlDbType.VarChar), out var items))
            {
                return true;
			}
			return false;
		}
 
        public bool DeleteBylast_modified_by(string last_modified_by)
        {
            if (BaseDelete(new DeleteColumn(nameof(organisation_data__entityDbModel.last_modified_by), last_modified_by, MySqlDbType.VarChar), out var items))
            {
                return true;
			}
			return false;
		}


        public bool Merge(List<organisation_data__entityDbModel> items)
        {

            var mergeTable = new List<object[]>();
            var updates = items.Where(x => x.id != default).GroupBy(x => x.id).Select(x => x.Last());
            foreach (var item in items.Where(x => x.id == default).Union(updates))
            {
                mergeTable.Add(new object[]
                {
					item.id,
					item.code, item.DirtyColumns.Contains("code"),
					item.name, item.DirtyColumns.Contains("name"),
					item.entity_definition_id, item.DirtyColumns.Contains("entity_definition_id"),
					item.is_deleted, item.DirtyColumns.Contains("is_deleted"),
					item.created, item.DirtyColumns.Contains("created"),
					item.last_modified, item.DirtyColumns.Contains("last_modified"),
					item.all_identifiers, item.DirtyColumns.Contains("all_identifiers"),
					item.all_attributes, item.DirtyColumns.Contains("all_attributes"),
					item.created_by, item.DirtyColumns.Contains("created_by"),
					item.last_modified_by, item.DirtyColumns.Contains("last_modified_by")

                });
            }
            return BaseMerge(mergeTable);
        }
        public bool Merge(string csvPath)
        {
            var mergeTable = new List<object[]>();
            using (var sr = new StreamReader(csvPath))
            {
                var line = sr.ReadLine();
                if (line == null) return false;

                var firstItem = line.Split(',')[0];
                if (firstItem == "id")
                {
                    //CSV has headers
                    //Run to the next line
                    line = sr.ReadLine();
                    if (line == null) return true;
                }

                do
                {
                    var blocks = line.Split(',');
                    mergeTable.Add(new object[]
                    {
                        Cast<long>(blocks[0]),
                        Cast<long>(blocks[1]), true,
                    });
                } while ((line = sr.ReadLine()) != null);


                return BaseMerge(mergeTable);
            }
        }


        public IEnumerable<organisation_data__entityDbModel> Search(
            string code = null,
            string name = null,
            long? entity_definition_id = null,
            bool? is_deleted = null,
            DateTime? created = null,
            DateTime? last_modified = null,
            string all_identifiers = null,
            string all_attributes = null,
            string created_by = null,
            string last_modified_by = null)
        {
            var queries = new List<QueryItem>();

            if (code != null)
            queries.Add(new QueryItem(nameof(organisation_data__entityDbModel.code), code));
            if (name != null)
            queries.Add(new QueryItem(nameof(organisation_data__entityDbModel.name), name));
            if (entity_definition_id.HasValue)
            queries.Add(new QueryItem(nameof(organisation_data__entityDbModel.entity_definition_id), entity_definition_id));
            if (is_deleted.HasValue)
            queries.Add(new QueryItem(nameof(organisation_data__entityDbModel.is_deleted), is_deleted));
            if (created.HasValue)
            queries.Add(new QueryItem(nameof(organisation_data__entityDbModel.created), created));
            if (last_modified.HasValue)
            queries.Add(new QueryItem(nameof(organisation_data__entityDbModel.last_modified), last_modified));
            if (all_identifiers != null)
            queries.Add(new QueryItem(nameof(organisation_data__entityDbModel.all_identifiers), all_identifiers));
            if (all_attributes != null)
            queries.Add(new QueryItem(nameof(organisation_data__entityDbModel.all_attributes), all_attributes));
            if (created_by != null)
            queries.Add(new QueryItem(nameof(organisation_data__entityDbModel.created_by), created_by));
            if (last_modified_by != null)
            queries.Add(new QueryItem(nameof(organisation_data__entityDbModel.last_modified_by), last_modified_by));

            return BaseSearch(queries);
        }


 
        public IEnumerable<organisation_data__entityDbModel> FindBycode(string code)
        {
            return FindBycode(FindComparison.Equals, code);
        }

        public IEnumerable<organisation_data__entityDbModel> FindBycode(FindComparison comparison, string code)
        {
            var items = Where(nameof(organisation_data__entityDbModel.code), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), code).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__entityDbModel> FindByname(string name)
        {
            return FindByname(FindComparison.Equals, name);
        }

        public IEnumerable<organisation_data__entityDbModel> FindByname(FindComparison comparison, string name)
        {
            var items = Where(nameof(organisation_data__entityDbModel.name), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), name).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__entityDbModel> FindByentity_definition_id(long entity_definition_id)
        {
            return FindByentity_definition_id(FindComparison.Equals, entity_definition_id);
        }

        public IEnumerable<organisation_data__entityDbModel> FindByentity_definition_id(FindComparison comparison, long entity_definition_id)
        {
            var items = Where(nameof(organisation_data__entityDbModel.entity_definition_id), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), entity_definition_id).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__entityDbModel> FindByis_deleted(bool is_deleted)
        {
            return FindByis_deleted(FindComparison.Equals, is_deleted);
        }

        public IEnumerable<organisation_data__entityDbModel> FindByis_deleted(FindComparison comparison, bool is_deleted)
        {
            var items = Where(nameof(organisation_data__entityDbModel.is_deleted), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), is_deleted).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__entityDbModel> FindBycreated(DateTime created)
        {
            return FindBycreated(FindComparison.Equals, created);
        }

        public IEnumerable<organisation_data__entityDbModel> FindBycreated(FindComparison comparison, DateTime created)
        {
            var items = Where(nameof(organisation_data__entityDbModel.created), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), created).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__entityDbModel> FindBylast_modified(DateTime last_modified)
        {
            return FindBylast_modified(FindComparison.Equals, last_modified);
        }

        public IEnumerable<organisation_data__entityDbModel> FindBylast_modified(FindComparison comparison, DateTime last_modified)
        {
            var items = Where(nameof(organisation_data__entityDbModel.last_modified), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), last_modified).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__entityDbModel> FindByall_identifiers(string all_identifiers)
        {
            return FindByall_identifiers(FindComparison.Equals, all_identifiers);
        }

        public IEnumerable<organisation_data__entityDbModel> FindByall_identifiers(FindComparison comparison, string all_identifiers)
        {
            var items = Where(nameof(organisation_data__entityDbModel.all_identifiers), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), all_identifiers).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__entityDbModel> FindByall_attributes(string all_attributes)
        {
            return FindByall_attributes(FindComparison.Equals, all_attributes);
        }

        public IEnumerable<organisation_data__entityDbModel> FindByall_attributes(FindComparison comparison, string all_attributes)
        {
            var items = Where(nameof(organisation_data__entityDbModel.all_attributes), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), all_attributes).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__entityDbModel> FindBycreated_by(string created_by)
        {
            return FindBycreated_by(FindComparison.Equals, created_by);
        }

        public IEnumerable<organisation_data__entityDbModel> FindBycreated_by(FindComparison comparison, string created_by)
        {
            var items = Where(nameof(organisation_data__entityDbModel.created_by), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), created_by).Results();
			return items;
        }
 
        public IEnumerable<organisation_data__entityDbModel> FindBylast_modified_by(string last_modified_by)
        {
            return FindBylast_modified_by(FindComparison.Equals, last_modified_by);
        }

        public IEnumerable<organisation_data__entityDbModel> FindBylast_modified_by(FindComparison comparison, string last_modified_by)
        {
            var items = Where(nameof(organisation_data__entityDbModel.last_modified_by), (Comparison)Enum.Parse(typeof(Comparison), comparison.ToString()), last_modified_by).Results();
			return items;
        }


        public override organisation_data__entityDbModel ToItem(DataRow row, bool skipBase)
        {
            var item = new organisation_data__entityDbModel();
            item.id = GetInt64(row, "id");
            item.code = GetString(row, "code");
            item.name = GetString(row, "name");
            item.entity_definition_id = GetInt64(row, "entity_definition_id");
            item.is_deleted = GetBoolean(row, "is_deleted");
            item.created = GetDateTime(row, "created");
            item.last_modified = GetDateTime(row, "last_modified");
            item.all_identifiers = GetString(row, "all_identifiers");
            item.all_attributes = GetString(row, "all_attributes");
            item.created_by = GetString(row, "created_by");
            item.last_modified_by = GetString(row, "last_modified_by");

            item.ResetDirty();
            return item;
        }

		public override TK ToItem<TK>(DataRow row, bool skipBase)
		{
            var item = new TK();
            item.id = GetInt64(row, "id");
            item.code = GetString(row, "code");
            item.name = GetString(row, "name");
            item.entity_definition_id = GetInt64(row, "entity_definition_id");
            item.is_deleted = GetBoolean(row, "is_deleted");
            item.created = GetDateTime(row, "created");
            item.last_modified = GetDateTime(row, "last_modified");
            item.all_identifiers = GetString(row, "all_identifiers");
            item.all_attributes = GetString(row, "all_attributes");
            item.created_by = GetString(row, "created_by");
            item.last_modified_by = GetString(row, "last_modified_by");

			item.ResetDirty();
			return item as TK;
		}

    }
}