//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Xml;
using Biomind.Data.Models.Base;
using MySqlConnector;

namespace Biomind.Data.Models
{
	public partial class organisation_data__categoryDbModel : BaseModel
	{
		public override string EntityName => "organisation_data__category";

		public static string CacheKey(long id) => $"organisation_data__category_{id}";
        protected long _id;
        protected string _code;
        protected string _name;
        protected string _last_modified_by;
        protected bool _is_deleted;
        protected DateTime _created;
        protected DateTime _last_modified;
        protected long? _category_group_id;
        protected string _created_by;
        protected short _colour_number;
        protected bool _is_system;

		public long id
		{
			get => _id;
			set => SetValue(ref _id, value);
		}
		public string code
		{
			get => _code;
			set => SetValue(ref _code, value);
		}
		public string name
		{
			get => _name;
			set => SetValue(ref _name, value);
		}
		public string last_modified_by
		{
			get => _last_modified_by;
			set => SetValue(ref _last_modified_by, value);
		}
		public bool is_deleted
		{
			get => _is_deleted;
			set => SetValue(ref _is_deleted, value);
		}
		public DateTime created
		{
			get => _created;
			set => SetValue(ref _created, value);
		}
		public DateTime last_modified
		{
			get => _last_modified;
			set => SetValue(ref _last_modified, value);
		}
		public long? category_group_id
		{
			get => _category_group_id;
			set => SetValue(ref _category_group_id, value);
		}
		public string created_by
		{
			get => _created_by;
			set => SetValue(ref _created_by, value);
		}
		public short colour_number
		{
			get => _colour_number;
			set => SetValue(ref _colour_number, value);
		}
		public bool is_system
		{
			get => _is_system;
			set => SetValue(ref _is_system, value);
		}
		
		public organisation_data__categoryDbModel() { }
		public organisation_data__categoryDbModel(
            long id,
            string code,
            string name,
            string last_modified_by,
            bool is_deleted,
            DateTime created,
            DateTime last_modified,
            long? category_group_id,
            string created_by,
            short colour_number,
            bool is_system)
		{
            _id = id;
            _code = code;
            _name = name;
            _last_modified_by = last_modified_by;
            _is_deleted = is_deleted;
            _created = created;
            _last_modified = last_modified;
            _category_group_id = category_group_id;
            _created_by = created_by;
            _colour_number = colour_number;
            _is_system = is_system;
		}

		public override IBaseModel SetValues(DataRow row, string propertyPrefix)
		{
            _id = row.GetValue<long>($"{propertyPrefix}id") ?? default(long);
            _code = row.GetText($"{propertyPrefix}code");
            _name = row.GetText($"{propertyPrefix}name");
            _last_modified_by = row.GetText($"{propertyPrefix}last_modified_by");
            _is_deleted = row.GetValue<bool>($"{propertyPrefix}is_deleted") ?? default(bool);
            _created = row.GetValue<DateTime>($"{propertyPrefix}created") ?? default(DateTime);
            _last_modified = row.GetValue<DateTime>($"{propertyPrefix}last_modified") ?? default(DateTime);
            _category_group_id = row.GetValue<long>($"{propertyPrefix}category_group_id");
            _created_by = row.GetText($"{propertyPrefix}created_by");
            _colour_number = row.GetValue<short>($"{propertyPrefix}colour_number") ?? default(short);
            _is_system = row.GetValue<bool>($"{propertyPrefix}is_system") ?? default(bool);
			return this;
		}

		public override List<ValidationError> Validate()
		{
			var validationErrors = new List<ValidationError>();

			if (code == null)
				validationErrors.Add(new ValidationError(nameof(code), "Value cannot be null"));
			if (!string.IsNullOrEmpty(code) && code.Length > 50)
				validationErrors.Add(new ValidationError(nameof(code), "Max length is 50"));

			if (!string.IsNullOrEmpty(name) && name.Length > 4000)
				validationErrors.Add(new ValidationError(nameof(name), "Max length is 4000"));

			if (last_modified_by == null)
				validationErrors.Add(new ValidationError(nameof(last_modified_by), "Value cannot be null"));
			if (!string.IsNullOrEmpty(last_modified_by) && last_modified_by.Length > 36)
				validationErrors.Add(new ValidationError(nameof(last_modified_by), "Max length is 36"));

			if (created == DateTime.MinValue)
				validationErrors.Add(new ValidationError(nameof(created), "Value cannot be default."));
			if (last_modified == DateTime.MinValue)
				validationErrors.Add(new ValidationError(nameof(last_modified), "Value cannot be default."));
			if (created_by == null)
				validationErrors.Add(new ValidationError(nameof(created_by), "Value cannot be null"));
			if (!string.IsNullOrEmpty(created_by) && created_by.Length > 36)
				validationErrors.Add(new ValidationError(nameof(created_by), "Max length is 36"));

			return validationErrors;
		}

		public static string Schema = "democlient";
		public static string TableName = "organisation_data__category";
		public static List<ColumnDefinition> Columns => new List<ColumnDefinition>
		{
			new ColumnDefinition("id", typeof(long), "[bigint]", MySqlDbType.Int64, false, true, true),
			new ColumnDefinition("code", typeof(string), "[varchar](50)", MySqlDbType.VarChar, false, false, false),
			new ColumnDefinition("name", typeof(string), "[varchar](4000)", MySqlDbType.VarChar, true, false, false),
			new ColumnDefinition("last_modified_by", typeof(string), "[char](36)", MySqlDbType.VarChar, false, false, false),
			new ColumnDefinition("is_deleted", typeof(bool), "[bit]", MySqlDbType.Bit, false, false, false),
			new ColumnDefinition("created", typeof(DateTime), "[timestamp]", MySqlDbType.Timestamp, false, false, false),
			new ColumnDefinition("last_modified", typeof(DateTime), "[timestamp]", MySqlDbType.Timestamp, false, false, false),
			new ColumnDefinition("category_group_id", typeof(long), "[bigint]", MySqlDbType.Int64, true, false, false),
			new ColumnDefinition("created_by", typeof(string), "[char](36)", MySqlDbType.VarChar, false, false, false),
			new ColumnDefinition("colour_number", typeof(short), "[smallint]", MySqlDbType.Int16, false, false, false),
			new ColumnDefinition("is_system", typeof(bool), "[bit]", MySqlDbType.Bit, false, false, false),

		};
	}
}

