//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Data;
using System.Xml;
using Biomind.Data.Models.Base;
using MySqlConnector;

namespace Biomind.Data.Models
{
	public partial class organisation_data__originatorDbModel : BaseModel
	{
		public override string EntityName => "organisation_data__originator";

		public static string CacheKey(long id) => $"organisation_data__originator_{id}";
        protected long _id;
        protected string _name;
        protected string _alias;
        protected string _last_modified_by;
        protected DateTime _last_modified;
        protected DateTime _created;
        protected string _created_by;

		public long id
		{
			get => _id;
			set => SetValue(ref _id, value);
		}
		public string name
		{
			get => _name;
			set => SetValue(ref _name, value);
		}
		public string alias
		{
			get => _alias;
			set => SetValue(ref _alias, value);
		}
		public string last_modified_by
		{
			get => _last_modified_by;
			set => SetValue(ref _last_modified_by, value);
		}
		public DateTime last_modified
		{
			get => _last_modified;
			set => SetValue(ref _last_modified, value);
		}
		public DateTime created
		{
			get => _created;
			set => SetValue(ref _created, value);
		}
		public string created_by
		{
			get => _created_by;
			set => SetValue(ref _created_by, value);
		}
		
		public organisation_data__originatorDbModel() { }
		public organisation_data__originatorDbModel(
            long id,
            string name,
            string alias,
            string last_modified_by,
            DateTime last_modified,
            DateTime created,
            string created_by)
		{
            _id = id;
            _name = name;
            _alias = alias;
            _last_modified_by = last_modified_by;
            _last_modified = last_modified;
            _created = created;
            _created_by = created_by;
		}

		public override IBaseModel SetValues(DataRow row, string propertyPrefix)
		{
            _id = row.GetValue<long>($"{propertyPrefix}id") ?? default(long);
            _name = row.GetText($"{propertyPrefix}name");
            _alias = row.GetText($"{propertyPrefix}alias");
            _last_modified_by = row.GetText($"{propertyPrefix}last_modified_by");
            _last_modified = row.GetValue<DateTime>($"{propertyPrefix}last_modified") ?? default(DateTime);
            _created = row.GetValue<DateTime>($"{propertyPrefix}created") ?? default(DateTime);
            _created_by = row.GetText($"{propertyPrefix}created_by");
			return this;
		}

		public override List<ValidationError> Validate()
		{
			var validationErrors = new List<ValidationError>();

			if (name == null)
				validationErrors.Add(new ValidationError(nameof(name), "Value cannot be null"));
			if (!string.IsNullOrEmpty(name) && name.Length > 255)
				validationErrors.Add(new ValidationError(nameof(name), "Max length is 255"));

			if (alias == null)
				validationErrors.Add(new ValidationError(nameof(alias), "Value cannot be null"));
			if (!string.IsNullOrEmpty(alias) && alias.Length > 255)
				validationErrors.Add(new ValidationError(nameof(alias), "Max length is 255"));

			if (last_modified_by == null)
				validationErrors.Add(new ValidationError(nameof(last_modified_by), "Value cannot be null"));
			if (!string.IsNullOrEmpty(last_modified_by) && last_modified_by.Length > 36)
				validationErrors.Add(new ValidationError(nameof(last_modified_by), "Max length is 36"));

			if (last_modified == DateTime.MinValue)
				validationErrors.Add(new ValidationError(nameof(last_modified), "Value cannot be default."));
			if (created == DateTime.MinValue)
				validationErrors.Add(new ValidationError(nameof(created), "Value cannot be default."));
			if (created_by == null)
				validationErrors.Add(new ValidationError(nameof(created_by), "Value cannot be null"));
			if (!string.IsNullOrEmpty(created_by) && created_by.Length > 36)
				validationErrors.Add(new ValidationError(nameof(created_by), "Max length is 36"));

			return validationErrors;
		}

		public static string Schema = "democlient";
		public static string TableName = "organisation_data__originator";
		public static List<ColumnDefinition> Columns => new List<ColumnDefinition>
		{
			new ColumnDefinition("id", typeof(long), "[bigint]", MySqlDbType.Int64, false, true, true),
			new ColumnDefinition("name", typeof(string), "[varchar](255)", MySqlDbType.VarChar, false, false, false),
			new ColumnDefinition("alias", typeof(string), "[varchar](255)", MySqlDbType.VarChar, false, false, false),
			new ColumnDefinition("last_modified_by", typeof(string), "[char](36)", MySqlDbType.VarChar, false, false, false),
			new ColumnDefinition("last_modified", typeof(DateTime), "[timestamp]", MySqlDbType.Timestamp, false, false, false),
			new ColumnDefinition("created", typeof(DateTime), "[timestamp]", MySqlDbType.Timestamp, false, false, false),
			new ColumnDefinition("created_by", typeof(string), "[char](36)", MySqlDbType.VarChar, false, false, false),

		};
	}
}

